### ISSUE TITLE
Inappropriate text and personally identifiable information

### ISSUE THREAD

**Issue by altilunium** [IndoNLP/nusa-writes#18]
While reviewing the dataset, I found several instances of [inappropriate text](https://github.com/search?q=repo%3AIndoNLP%2Fnusa-writes+%22gmn+ngga+coli%22&type=code) with personally identifiable information still intact in the dataset.

Do you have any plans to remove this from the dataset?

**Comment by SamuelCahyawijaya** [comment]
@altilunium : for the `nusa-kalimat` (a.k.a. NusaTranslation) subset, we didn't make any changes from the original dataset source (i.e., [EmoT[(https://indonlp.github.io/nusa-catalogue/card.html?emot) and [IndoLEM Sentiment](https://indonlp.github.io/nusa-catalogue/card.html?indolem_sentiment)). We have no plan to clean up the data as it will not reflect the resulting analysis in our paper.

However, we would like to encourage future researchers, especially those focusing on NLP applications, to exercise caution and be aware of the potentially toxic, profane, and other inappropriate contents that may exist in our dataset.

Hope it helps!
