### ISSUE TITLE
Both `load_benchmark('NusaTranslation')` and `load_benchmark('NusaWrites')` tries to download a file that does not exist

### ISSUE THREAD

**Issue by ShandyDrm** [IndoNLP/nusa-writes#19]
Python 3.10, NusaCrowd 0.1.2

Error message:  
`FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/IndoNLP/nusa-writes/main/data/nusa_kalimat-mt-bug-train.csv`

<img width="1327" alt="Screenshot 2023-12-15 at 20 34 56 copy" src="https://github.com/IndoNLP/nusa-writes/assets/23477197/34c61a64-4e87-41cc-a70b-600a192c80ef">

**Comment by SamuelCahyawijaya** [comment]
Hi @ShandyDrm , thanks for reporting. 

We have fixed the problem and you can try installing the new version `nusacrowd==0.1.3`

Please let us know if you find any further problems.
